# Generated by Django 5.0.7 on 2024-08-02 02:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='group_members',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='id',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='total_members',
        ),
        migrations.AddField(
            model_name='groups',
            name='image',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groups',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_table_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='groups.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
